### ISSUE TITLE
Comienzo del proyecto

### ISSUE THREAD

**Issue by luedu1103** [Web-EN/Netnious#2]
Desde hoy se comenzará con el desarrollo activo del proyecto Netnious, nos dividiremos en dos equipos. Uno dedicado al backend y el otro dedicado al frontend.

**Comment by luedu1103** [comment]
Lo primero que realizaremos será configurar el set up en el cual vamos a desarrollar, para eso, confío en @vizcacha22 subirá al main todo lo necesario para poder correr un simple hola mundo con flutter. Una vez este hecho esto, quiero que todos manden foto del hola mundo en sus computadoras, para confirmar que podemos dar inicio al desarrollo de la aplicación
Van marcando completado aquí abajo y suben en un comentario aparte captura de su hola mundo con flutter.
- [x] @sebauvv 
- [x] @vizcacha22 
- [x] @GiovanniCorone1 
- [x] @FranzARCH 
- [x] @AlvaroChavezCc 
- [x] @rodcz 
- [x] @LeonidCJ 
- [x] @davidcsns 
- [x] @ProtoSG

**Comment by davidcsns** [comment]
![Image](https://github.com/Web-EN/Netnious/assets/143876605/b4464d8f-1a24-4709-894a-f6a998ce800c)

**Comment by rodcz** [comment]
![image](https://github.com/Web-EN/Netnious/assets/143662411/01e7543f-5686-42e4-a9af-f8dd2bb0d7e9)

**Comment by GiovanniCorone1** [comment]
![IMAflutterholamundo_page-0001](https://github.com/Web-EN/Netnious/assets/121734836/1809be0f-da65-4a5c-b525-11074958c697)

**Comment by ProtoSG** [comment]
![HolaMundo](https://github.com/Web-EN/Netnious/assets/143894337/26440b62-bb2a-44f0-a04c-5fd0d9042d7c)

**Comment by FranzARCH** [comment]
![image](https://github.com/Web-EN/Netnious/assets/130520660/5e52dec1-7f36-4110-9acd-542053e07f4b)

**Comment by LeonidCJ** [comment]
![image](https://github.com/Web-EN/Netnious/assets/143663889/2d463a96-3f1a-4442-baf8-85d73bfe934e)

**Comment by alvaro-chz** [comment]
![image](https://github.com/Web-EN/Netnious/assets/135331266/2d17e013-cf24-405b-9334-9288c6a97448)

**Comment by sebauvv** [comment]
![image](https://github.com/Web-EN/Netnious/assets/109055595/4f2e5ef8-0ad4-4c37-8351-83381395ad5f)
